import type { ClientTableView, PokerTableConfig } from '@/shared/pookie-poker'
import { DEFAULT_POKIE_POKER_RAKE } from '@/shared/pookie-poker'

export const POKIE_POKER_LOBBY_TABLES: PokerTableConfig[] = [
  {
    tableId: 'neon-rooftop-1',
    tableName: 'Neon Rooftop 1',
    tableType: 'public',
    gameType: 'texas_holdem',
    currency: 'SOL',
    smallBlindLamports: '5000000',
    bigBlindLamports: '10000000',
    minBuyInLamports: '200000000',
    maxBuyInLamports: '1000000000',
    maxPlayers: 6,
    rake: DEFAULT_POKIE_POKER_RAKE,
    realMoneyEnabled: false,
    compliancePolicy: {
      requiresKyc: false,
      requiresGeofence: false,
      allowSpectators: true,
    },
  },
  {
    tableId: 'private-lounge-preview',
    tableName: 'Private Lounge Preview',
    tableType: 'private',
    inviteCode: 'POOKIE',
    gameType: 'texas_holdem',
    currency: 'SOL',
    smallBlindLamports: '1000000',
    bigBlindLamports: '2000000',
    minBuyInLamports: '100000000',
    maxBuyInLamports: '500000000',
    maxPlayers: 6,
    rake: { ...DEFAULT_POKIE_POKER_RAKE, rakePercentBps: 150 },
    realMoneyEnabled: false,
    compliancePolicy: {
      requiresKyc: false,
      requiresGeofence: false,
      allowSpectators: false,
    },
  },
]

export const MOCK_TABLE_VIEW: ClientTableView = {
  tableId: 'neon-rooftop-1',
  tableName: 'Neon Rooftop 1',
  tableType: 'public',
  status: 'active',
  gameType: 'texas_holdem',
  currency: 'SOL',
  handNumber: 12,
  street: 'flop',
  smallBlindLamports: '5000000',
  bigBlindLamports: '10000000',
  minBuyInLamports: '200000000',
  maxBuyInLamports: '1000000000',
  maxPlayers: 6,
  potLamports: '185000000',
  sidePots: [],
  communityCards: [
    { rank: 'A', suit: 's' },
    { rank: 'T', suit: 'h' },
    { rank: '5', suit: 'd' },
  ],
  dealerSeat: 4,
  currentTurnSeat: 0,
  players: [
    {
      wallet: 'demo-local-wallet',
      displayName: 'You',
      seatIndex: 0,
      stackLamports: '815000000',
      currentBetLamports: '35000000',
      folded: false,
      allIn: false,
      connected: true,
      lastAction: 'raise',
    },
    {
      wallet: 'neon-caller',
      displayName: 'Neon Caller',
      seatIndex: 1,
      stackLamports: '620000000',
      currentBetLamports: '35000000',
      folded: false,
      allIn: false,
      connected: true,
      lastAction: 'call',
    },
    {
      wallet: 'glass-shark',
      displayName: 'Glass Shark',
      seatIndex: 2,
      stackLamports: '940000000',
      currentBetLamports: '0',
      folded: true,
      allIn: false,
      connected: true,
      lastAction: 'fold',
    },
    {
      wallet: 'palm-bandit',
      displayName: 'Palm Bandit',
      seatIndex: 4,
      stackLamports: '450000000',
      currentBetLamports: '0',
      folded: false,
      allIn: false,
      connected: true,
      lastAction: 'check',
    },
  ],
  rakeInfo: {
    rakeBps: 400,
    rakeCapLamports: '30000000',
    rakeTakenThisHandLamports: '0',
  },
  me: {
    wallet: 'demo-local-wallet',
    displayName: 'You',
    seatIndex: 0,
    stackLamports: '815000000',
    currentBetLamports: '35000000',
    folded: false,
    allIn: false,
    connected: true,
    lastAction: 'raise',
    holeCards: [
      { rank: 'Q', suit: 'h' },
      { rank: 'J', suit: 's' },
    ],
  },
  legalActions: [
    { type: 'fold' },
    { type: 'call', minAmountLamports: '35000000', maxAmountLamports: '35000000' },
    { type: 'raise', minAmountLamports: '70000000', maxAmountLamports: '815000000' },
    { type: 'allin', maxAmountLamports: '815000000' },
  ],
}

